# Generated by Django 3.2.20 on 2023-08-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20230802_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Enter maximum number of students. Leave blank for open enrollment.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='open_enrollment',
            field=models.BooleanField(default=True),
        ),
    ]
