# Generated by Django 3.2.20 on 2023-08-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_frequency',
        ),
        migrations.RemoveField(
            model_name='course',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_in_weeks',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrolled_students_count',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level_of_difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='open_enrollment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
    ]
