# Generated by Django 3.2.20 on 2023-08-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20230802_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enroll',
            field=models.ManyToManyField(related_name='_accounts_course_enroll_+', to='accounts.Course'),
        ),
    ]
