# Generated by Django 3.2.20 on 2023-08-03 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230802_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students_enrolled',
        ),
    ]
