# Generated by Django 3.2.20 on 2023-08-03 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20230803_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='accounts.coursecategory')),
            ],
            options={
                'verbose_name_plural': 'Course Subcategories',
            },
        ),
    ]
