# Generated by Django 3.2.20 on 2023-08-03 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20230803_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coursecategory'),
        ),
        migrations.DeleteModel(
            name='CourseSubcategory',
        ),
    ]
