# Generated by Django 3.2.20 on 2023-08-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0027_auto_20230803_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_frequency',
            field=models.PositiveIntegerField(blank=True, help_text='Enter how often the class will meet per week.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_in_weeks',
            field=models.PositiveIntegerField(blank=True, help_text='Enter length of the course in weeks.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_of_difficulty',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Enter maximum number of students. Leave blank for open enrollment.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='open_enrollment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
