# Generated by Django 3.2.20 on 2023-08-06 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In-person'), ('HYBRID', 'Hybrid')], default='ONLINE', max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_meeting_schedule', to='accounts.course')),
            ],
            options={
                'verbose_name': 'Class Meeting',
                'verbose_name_plural': 'Class Meetings',
            },
        ),
    ]
