# Generated by Django 3.2.20 on 2023-08-06 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_classmeetings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassMeetings',
            new_name='ClassMeeting',
        ),
    ]
