# Generated by Django 3.2.20 on 2023-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_rename_classmeetings_classmeeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='No Course Descripton.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='No Title', max_length=200),
            preserve_default=False,
        ),
    ]
