# Generated by Django 3.2.20 on 2023-08-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20230807_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmeeting',
            name='end_time_meridiem',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='classmeeting',
            name='start_time_meridiem',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True),
        ),
    ]
