# Generated by Django 3.2.20 on 2023-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_rename_classmeeting_groupstudymeeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstudymeeting',
            options={'verbose_name': 'Group Meeting', 'verbose_name_plural': 'Group Meetings'},
        ),
        migrations.AlterField(
            model_name='groupstudymeeting',
            name='end_time_meridiem',
            field=models.CharField(choices=[('--', '--'), ('AM', 'AM'), ('PM', 'PM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='groupstudymeeting',
            name='start_time_meridiem',
            field=models.CharField(choices=[('--', '--'), ('AM', 'AM'), ('PM', 'PM')], max_length=2),
        ),
    ]
