# Generated by Django 3.2.20 on 2023-08-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20230808_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudymeeting',
            name='end_time_meridiem',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='groupstudymeeting',
            name='start_time_meridiem',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2),
        ),
    ]
