# Generated by Django 3.2.20 on 2023-08-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20230811_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='user_interests', to='accounts.CourseCategory'),
        ),
    ]
