# Generated by Django 3.2.20 on 2023-08-13 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0044_groupstudymeeting_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRequestAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('study_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.groupstudymeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('study_request', 'user')},
            },
        ),
    ]
