# Generated by Django 3.2.20 on 2023-08-14 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_studyrequestacceptance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyrequestacceptance',
            options={'verbose_name_plural': 'Study Request Acceptances'},
        ),
        migrations.AddField(
            model_name='studyrequestacceptance',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_request_acceptances', to='accounts.course'),
        ),
    ]
