# Generated by Django 3.2.20 on 2023-08-14 05:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0046_auto_20230814_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
