# Generated by Django 3.2.20 on 2023-08-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_profile_instagram_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interested_categories',
            field=models.ManyToManyField(blank=True, to='accounts.CourseCategory'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level_of_difficulty',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=13, null=True),
        ),
    ]
