# Generated by Django 3.2.20 on 2023-08-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_comment_course'),
        ('accounts', '0049_auto_20230815_0619'),
    ]

    operations = [
    ]
